### ISSUE TITLE
CalendarInput min date limits selectable month to month after min date. 

### ISSUE THREAD

**Issue by FelixLetheren** [Rocketmakers/armstrong#80]
1. Have a min and max calander date set in different months. 
2. Use the back arrow to select the min date.
3. The calander will only allow you back as far as the month afterwards.

In this example the min date is the 17th September 2019:
<img width="519" alt="Screenshot 2019-11-26 at 16 38 36" src="https://user-images.githubusercontent.com/52042291/69653565-5281ba00-106b-11ea-83dc-6f37d8fecb26.png">
<img width="450" alt="Screenshot 2019-11-26 at 16 38 43" src="https://user-images.githubusercontent.com/52042291/69653572-56154100-106b-11ea-83e2-228ac9a104d9.png">

**Comment by adamiprinciples** [comment]
Fixed by vinces MR above ^
